module: KituraStencil
author: IBM and the Kitura project authors
github_url: https://github.com/Kitura/Kitura-StencilTemplateEngine/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraStencil.xcodeproj, -target, KituraStencil, LIBRARY_SEARCH_PATHS=.build/debug]

