module: KituraStencil
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-StencilTemplateEngine.xcodeproj, -target, KituraStencil, LIBRARY_SEARCH_PATHS=.build/debug]

